file = open("output.txt","w")
user = input("Enter text to write in the file: ")
write = file.write(user)
print("Data successfully written in the output.txt")
file.close()
file1 = open("output.txt","a")
user2 = input("Enter what you want to append in the file: ")
write2 = file1.write(user2)
print("Data successfully appended.")
file1.close()
file3 = open("output.txt",'r')
read = file3.read()
print("Final content of the file is. \n",read)
file3.close()